const data = {
  users: [
     {
      fullname:'ozioko blessing',
      email:'ada24@gmail.com',
      username:'adanna24',
      password:'234561',
      isAdmin: true,
     },
     {
      fullname:'Adanna savior',
      email:'bizzy@gmail.com',
      username:'bizzy',
      password:'78990vv',
      isAdmin: false,
     },
  ],
  products: [
    {
      name: 'ink women shoes ',
      category: 'female shoes',
      brand: 'jueszz',
      class:'heels',
      price:6000,
      details:'square poster flowers floral leaf shoe glass leaves banner female lines footwear nature pattern colorful mens shoes decorations woman',
      quantity:1,
      img:'https://toppng.com/uploads/preview/ink-women-shoes-png-image-women-shoes-transparent-background-11563550651v41t0milf1.png',
      review:10,
      rating:3,
    },
    {
      name:'red classy heels',
      category:'female shoes',
      brand:'kelz',
      class:'heels',
      price:6500,
      details:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque urna turpis, tempus vel mi a, pellentesque dignissim metus. Ut varius varius cursus. Fusce at tellus mi. Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://www.seekpng.com/png/detail/4-40295_women-shoes-image-wedding-transparent-background-ladies-shoes.png',
      review:40,
      rating:4,
    },
    {
      name:'low feels shoe',
      category:'female shoes',
      brand:'uxfs',
      class:'flats',
      price:2500,
      details:'Duis nec molestie justo. Nunc vehicula magna nec odio porttitor, sagittis sollicitudin enim dignissim. Suspendisse at ante vitae arcu fermentum consectetur. Aenean dignissim nunc sit amet felis scelerisque dictum. Praesent at massa ac nibh dapibus laoreet. Cras et venenatis libero.',
      quantity:1,
      img:'https://www.freeiconspng.com/uploads/blue-women-flat-shoes-png-33.png',
      review:9,
      rating:2,
    },
    {
      name:'comfty footy',
      category:'female shoes',
      brand:'uxfs',
      class:'flats',
      price:2500,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://s.alicdn.com/@sc04/kf/H8ddef3dc84dc46919927f6758436e515h.jpg',
      review:15,
      rating:4,
    },
    {
      name:'marry mey tell',
      category:'female shoes',
      brand:'uxfs',
      class:'flats',
      price:3000,
      details:'Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. ',
      quantity:1,
      img:'https://ae01.alicdn.com/kf/HTB1vHxvbh2rK1RkSnhJq6ykdpXaZ/Tailored-2019-new-women-s-casual-flat-shoes-European-style-fashion-spring-pointed-women-s-shoes.jpg_Q90.jpg_.webp',
      review:20,
      rating:5,
    },
    {
      name:'lovely tellz',
      category:'female shoes',
      brand:'jueszz',
      class:'flats',
      price:3000,
      details:' Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'https://cf.shopee.com.my/file/8dfa1298ae38cb514dfedd9734a196cc',
      review:34,
      rating:5,
    },
    {
      name:'pointy toes classic',
      category:'female shoes',
      brand:'jueszz',
      class:'heels',
      price:3000,
      details:'Ut fringilla nec tortor at cursus. Pellentesque ligula nisl, malesuada ac felis feugiat, mollis iaculis turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In dictum erat eget tristique maximus. Maecenas non mattis mi. Duis rutrum ornare ligula sed convallis.',
      quantity:1,
      img:'https://freepngimg.com/thumb/women_shoes/1-2-women-shoes-free-png-image.png',
      review:30,
      rating:4,
    },
    {
      name:'wedding classic',
      category:'female shoes',
      brand:'guazrs',
      class:'heels',
      price:8000,
      details:'per inceptos himenaeos. In dictum erat eget tristique maximus. Maecenas non mattis mi. Duis rutrum ornare ligula sed convallis. Ut bibendum facilisis pellentesque. Nulla ac lobortis nisl. Morbi tincidunt et tortor non scelerisque. Nunc ac elit fermentum, imperdiet dui ac, semper urna. Vestibulum volutpat iaculis nisl in porttitor. Donec non risus est.',
      quantity:1,
      img:'https://p1.pxfuel.com/preview/244/355/775/fashion-high-heels-shoes-pumps-royalty-free-thumbnail.jpg',
      review:60,
      rating:4,
    },
    {
      name:'wedding classic gatty',
      category:'female shoes',
      brand:'guazrs',
      class:'heels',
      price:12000,
      details:'Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'https://toppng.com/uploads/preview/high-heel-shoes-11528495688ezvijnh4jh.png',
      review:40,
      rating:5,
    },
    {
      name:'nikky pinky',
      category:'female shoes',
      brand:'nike',
      class:'sneakers',
      price:8000,
      details:'Phasellus scelerisque egestas gravida. Mauris vehicula quis eros ac venenatis. Morbi eleifend lacus dolor, sed condimentum sapien facilisis a. Donec pharetra aliquam augue, dictum sagittis nibh pharetra non. Integer in pellentesque velit. Sed rhoncus sem quis lectus posuere venenatis. Proin posuere sapien vitae lorem venenatis, et condimentum ante consequat. Pellentesque eu arcu sit amet metus feugiat porta sed sit amet risus.',
      quantity:1,
      img:'https://w7.pngwing.com/pngs/75/649/png-transparent-adidas-shoe-sneakers-women-shoes-purple-white-violet-thumbnail.png',
      review:20,
      rating:3,
    },
    
    {
      name:'red fisy toes',
      category:'female shoes',
      brand:'kwicky',
      class:'sneakers',
      price:4000,
      details:' Pellentesque ligula nisl, malesuada ac felis feugiat, mollis iaculis turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In dictum erat eget tristique maximus. Maecenas non mattis mi. Duis rutrum ornare ligula sed convallis. Ut bibendum facilisis pellentesque. Nulla ac lobortis nisl. Morbi tincidunt et tortor non scelerisque. Nunc ac elit fermentum, imperdiet dui ac, semper urna. ',
      quantity:1,
      img:'https://5.imimg.com/data5/WI/YD/MY-38674321/comfortable-basketball-shoes-500x500.jpg',
      review:10,
      rating:2,
    },
    {
      name:'gold michael cors',
      category:'female shoes',
      brand:'michael',
      class:'sneakers',
      price:4000,
      details:'malesuada ac felis feugiat, mollis iaculis turpis Pellentesque ligula nisl, malesuada ac felis feugiat, mollis iaculis turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In dictum erat eget tristique maximus. Maecenas non mattis mi. Duis rutrum ornare ligula sed convallis. Ut bibendum facilisis pellentesque. Nulla ac lobortis nisl. Morbi tincidunt et tortor non scelerisque. Nunc ac elit fermentum, imperdiet dui ac, semper urna. ',
      quantity:1,
      img:'https://www.pngkey.com/png/full/301-3017123_womens-shoes-gold-michael-kors-sneakers-poppy-lace.png',
      review:20,
      rating:3,
    },
    {
      name:'micheal fordees',
      category:'female shoes',
      brand:'michael',
      class:'sneakers',
      price:4000,
      details:' Pellentesque ligula nisl, malesuada ac felis feugiat, mollis iaculis turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In dictum erat eget tristique maximus. Maecenas non mattis mi. Duis rutrum ornare ligula sed convallis. Ut bibendum facilisis pellentesque. Nulla ac lobortis nisl. Morbi tincidunt et tortor non scelerisque. Nunc ac elit fermentum, imperdiet dui ac, semper urna. ',
      quantity:1,
      img:'https://di2ponv0v5otw.cloudfront.net/posts/2020/04/22/5ea098ce7d03b7cca0791a13/m_5ea098d19e1559e1349332df.jpeg',
      review:40,
      rating:4,
    },
    {
      name:'michael-kors-white',
      category:'female shoes',
      brand:'michael',
      class:'sneakers',
      price:9000,
      details:' Pellentesque ligula nisl, malesuada ac felis feugiat, mollis iaculis turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In dictum erat eget tristique maximus. Maecenas non mattis mi. Duis rutrum ornare ligula sed convallis. Ut bibendum facilisis pellentesque. Nulla ac lobortis nisl. Morbi tincidunt et tortor non scelerisque. Nunc ac elit fermentum, imperdiet dui ac, semper urna. ',
      quantity:1,
      img:'https://cdna.lystit.com/photos/d9c1-2014/12/02/michael-kors-white-michael-essex-high-top-sneakers-product-1-24454725-0-052499187-normal.jpeg',
      review:40,
      rating:4,
    },
    
    {
      name:'coffee alesso',
      category:'male shoes',
      brand:'red wing shoes',
      class:'leather',
      price:18000,
      details:'Nam ut velit at mi euismod ornare at ut quam. Nam est massa, bibendum ut felis at, pellentesque tincidunt est. Suspendisse efficitur, augue ac maximus euismod, libero orci condimentum diam, in rhoncus massa purus id enim. Sed non feugiat ante. ',
      quantity:1,
      img:'https://www.freeiconspng.com/uploads/men-shoes-png-free-download-14.png',
      review:40,
      rating:4,
    },
    
    {
      name:'black carlo',
      category:'male shoes',
      brand:'patent italian',
      class:'leather',
      price:20000,
      details:'Nam ut velit at mi euismod ornare Nam ut velit at mi euismod ornare Nam ut velit at mi euismod ornare at ut quam. Nam est massa, bibendum ut felis at, pellentesque tincidunt est. Suspendisse efficitur, augue ac maximus euismod, libero orci condimentum diam, in rhoncus massa purus id enim. Sed non feugiat ante. ',
      quantity:1,
      img:'https://pngimg.com/uploads/men_shoes/men_shoes_PNG7475.png',
      review:20,
      rating:4,
    },
    
    {
      name:'coffee artur',
      category:'male shoes',
      brand:'arsenio italian',
      class:'leather',
      price:18000,
      details:'Nam ut velit at mi euismod ornare Nam ut velit at mi euismod ornare In dictum erat eget tristique maximus. Maecenas non mattis mi. Duis rutrum ornare ligula sed convallis. Ut bibendum facilisis pellentesque. Nulla ac lobortis nisl. Morbi tincidunt et tortor non scelerisque. Nunc ac elit fermentum, imperdiet dui ac, semper urna. ',
      quantity:1,
      img:'https://www.freeiconspng.com/uploads/men-shoes-png-free-download-14.png',
      review:30,
      rating:5,
    },
    
    {
      name:'patent black carlo',
      category:'male shoes',
      brand:'dockers',
      class:'leather',
      price:12000,
      details:'Pellentesque mollis neque elit. Nullam quis dui porttitor, malesuada sapien in, lacinia massa. Nam ut velit at mi euismod ornare at ut quam. Nam est massa, bibendum ut felis at, pellentesque tincidunt est. Suspendisse efficitur, augue ac maximus euismod, libero orci condimentum diam, in rhoncus massa purus id enim. Sed non feugiat ante. Phasellus ac euismod nulla, lobortis placerat neque. Morbi sagittis ante nec lorem tempor, quis efficitur justo aliquam.',
      quantity:1,
      img:'https://pngimg.com/uploads/men_shoes/men_shoes_PNG7483.png',
      review:40,
      rating:4,
    },
    
    {
      name:'white adrain',
      category:'male shoes',
      brand:'rockport',
      class:'leather',
      price:17000,
      details:'Phasellus scelerisque egestas gravida. Mauris vehicula quis eros ac venenatis. Morbi eleifend lacus dolor, sed condimentum sapien facilisis a. Donec pharetra aliquam augue, dictum sagittis nibh pharetra non. Integer in pellentesque velit. Sed rhoncus sem quis lectus posuere venenatis. Proin posuere sapien vitae lorem venenatis, et condimentum ante consequat. Pellentesque eu arcu sit amet metus feugiat porta sed sit amet risus. Praesent vitae aliquet metus. Nam cursus orci quis nisl fermentum mollis. Nulla facilisis erat non nisi mattis convallis.',
      quantity:1,
      img:'https://www.pngall.com/wp-content/uploads/5/Sylish-Men-Shoes-PNG-Free-Image.png',
      review:40,
      rating:4,
    },
    
    {
      name:'oxford shoe',
      category:'male shoes',
      brand:'woven italian',
      class:'leather',
      price:19000,
      details:'Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae.',
      quantity:1,
      img:'https://www.pngall.com/wp-content/uploads/5/Men-Shoes-PNG-Picture.png',
      review:40,
      rating:4,
    },
    
    {
      name:'black men sneakers',
      category:'male shoes',
      brand:'leather sneakers',
      class:'sneakers',
      price:12000,
      details:'Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'https://image.similarpng.com/very-thumbnail/2020/09/Black-mens-leather-sneakers-isolated-on-transparent-background-PNG.png',
      review:30,
      rating:5,
    },
    
    {
      name:'porttitir sed',
      category:'male shoes',
      brand:'addidas',
      class:'sneakers',
      price:22000,
      details:'Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'https://png.pngtree.com/element_our/20190528/ourmid/pngtree-a-pair-of-shoes-image_1132125.jpg',
      review:40,
      rating:4,
    },
    
    {
      name:'swoosh nike runner',
      category:'male shoes',
      brand:'nike',
      class:'sneakers',
      price:15000,
      details:'Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'https://www.swooshstore.com/images/Nike-Free-Run-2-a.jpg',
      review:23,
      rating:5,
    },
    
    {
      name:'nancy collection',
      category:'male shoes',
      brand:'nancy',
      class:'sneakers',
      price:23000,
      details:'Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'https://nancy5710.typepad.com/.a/6a015390410589970b0154344b3bb5970c-pi',
      review:40,
      rating:4,
    },
    
    {
      name:'nike grey men',
      category:'male shoes',
      brand:'nike',
      class:'sneakers',
      price:23000,
      details:'Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'http://1.bp.blogspot.com/-hNJg4-RCxJY/TukKy9waxhI/AAAAAAAADLw/nM2CaYezMU4/s1600/nike_free_2_men_grey_navy_white.jpg',
      review:10,
      rating:4,
    },
    
    {
      name:'nike lunar glide',
      category:'male shoes',
      brand:'nike',
      class:'sneakers',
      price:12000,
      details:'Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'https://s3.amazonaws.com/nikeinc/assets/3856/11026_Nike_LunarGlide_Womens_lr_hd_1600.jpg',
      review:40,
      rating:4,
    },
    {
      name:'Red touch bag',
      category:'female bags',
      brand:'gubba',
      class:'fashion bag',
      price:12000,
      details:'Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar auris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvina. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'https://static-01.daraz.com.bd/p/2a18cfc5a1a16e4b9a66f85af35772d7.jpg',
      review:40,
      rating:4,
    },
    {
      name:'china classic',
      category:'female bags',
      brand:'chinnau',
      class:'fashion bag',
      price:12000,
      details:'Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar auris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvina. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar auris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvina. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'https://static-01.daraz.com.bd/p/11284d595dda5a1a944202be32c2441b.jpg',
      review:20,
      rating:4.5,

    },
    {
      name:'gigsy size shoot',
      category:'female bags',
      brand:'hussy',
      class:'fashion bag',
      price:17000,
      details:'Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar auris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvina. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar auris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvina. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar auris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvina. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.',
      quantity:1,
      img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv1o0ZjAWa4gvgeBvGvmV7u9Up4DZB_3uwm_ZduFdE6ks65VYmAPFSiKlEQVlJtPqpGz0&usqp=CAU',
      review:12,
      rating:2.5,

    },
    {
      name:'housee fun',
      category:'female bags',
      brand:'johnny',
      class:'fashion bag',
      price:2000,
      details:'Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar auris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvina. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar auris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvina. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida.Sed suscipit varius porttitor. Quisque ut nibh ac mauris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvinar auris fermentum vestibulum. Curabitur eu tellus et neque sagittis pulvina. In ut mollis erat. Praesent mi tellus, consequat eget vestibulum eu, rutrum sed ipsum. Etiam magna ligula, tincidunt et placerat vitae, aliquam eu quam. Ut ex libero, fermentum sit amet vulputate ac, dignissim vitae lectus. Ut at dui ac mi cursus convallis. Cras aliquet sapien mauris, ac vestibulum nibh rutrum vitae. Praesent velit ante, imperdiet in accumsan non, malesuada ut magna. Donec tincidunt ante sed lorem vehicula, quis auctor mauris fringilla. Nunc finibus eros vitae dui vestibulum gravida. ',
      quantity:1,
      img:'https://i.pinimg.com/originals/7f/7d/aa/7f7daa5af8a15203dab76565f4c50091.png',
      review:20,
      rating:4,

    },
    {
      name:'givenchi klohe',
      category:'female bags',
      brand:'johhny',
      class:'fashion bag',
      price:22000,
      details:'Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.Sed suscipit varius porttitor.v',
      quantity:1,
      img:'https://media1.popsugar-assets.com/files/thumbor/AvZEj7jpibblrfJAhs3wgqguGQE/fit-in/728xorig/filters:format_auto-!!-:strip_icc-!!-/2010/06/23/1/258/2589280/edf2b72246a84ac0_mulberrybags/i/How-Mulberry-Handbags-Priced-Why-Designer-Bags-Expensive.jpg',
      review:20,
      rating:4.5,

    },
    {
      name:'black pouche',
      category:'male bags',
      brand:'buxsz',
      class:'fashion bag',
      price:2300,
      details:'Phasellus scelerisque egestas gravida. Mauris vehicula quis eros ac venenatis. Morbi eleifend lacus dolor, sed condimentum sapien facilisis a. Donec pharetra aliquam augue, dictum sagittis nibh pharetra non. Integer in pellentesque velit. Sed rhoncus sem quis lectus posuer',
      quantity:1,
      img:'https://icon2.cleanpng.com/20180617/uaj/kisspng-briefcase-handbag-montblanc-meisterstck-men-bag-5b26053e7f0295.5761134715292183665202.jpg',
      review:30,
      rating:4.5,

    },
    {
      name:'addison big',
      category:'male bags',
      brand:'nuwst',
      class:'fashion bag',
      price:1000,
      details:'Phasellus scelerisque egestas gravida. Mauris vehicula quis eros ac venenatis. Morbi eleifend lacus dolor, sed condimentum sapien facilisis a. Donec pharetra aliquam augue, dictum sagittis nibh pharetra non. Integer in pellentesque velit. Sed rhoncus sem quis lectus posuer',
      quantity:1,
      img:'https://thumbs.dreamstime.com/b/classic-brown-leather-bag-classic-stylish-leather-brown-handle-bag-perspective-view-fashion-accessory-vector-illustration-173957089.jpg',
      review:30,
      rating:4.5,

    },{
      name:'clean cut',
      category:'male bags',
      brand:'kissy pearl',
      class:'fashion bag',
      price:20200,
      details:'Phasellus scelerisque egestas gravida. Mauris vehicula quis eros ac venenatis. Morbi eleifend lacus dolor, sed condimentum sapien facilisis a. Donec pharetra aliquam augue, dictum sagittis nibh pharetra non. Integer in pellentesque velit. Sed rhoncus sem quis lectus posuer',
      quantity:1,
      img:'https://icon2.cleanpng.com/20180723/rts/kisspng-handbag-leather-paska-messenger-bags-men-bag-5b569957957e32.6441422315324020076123.jpg',
      review:30,
      rating:4.5,

    },{
      name:'scelerisque egestes',
      category:'male bags',
      brand:'fr-cleeansy',
      class:'fashion bag',
      price:34500,
      details:'Phasellus scelerisque egestas gravida. Mauris vehicula quis eros ac venenatis. Morbi eleifend lacus dolor, sed condimentum sapien facilisis a. Donec pharetra aliquam augue, dictum sagittis nibh pharetra non. Integer in pellentesque velit. Sed rhoncus sem quis lectus posuer',
      quantity:1,
      img:'https://icon2.cleanpng.com/20180626/fr/kisspng-messenger-bags-handbag-leather-men-bag-5b3224ed4cab28.9679665715300129093141.jpg',
      review:30,
      rating:3.5,

    },{
      name:'atlas squid',
      category:'male bags',
      brand:'asset holder',
      class:'fashion bag',
      price:14500,
      details:'Phasellus scelerisque egestas gravida. Mauris vehicula quis eros ac venenatis. Morbi eleifend lacus dolor, sed condimentum sapien facilisis a. Donec pharetra aliquam augue, dictum sagittis nibh pharetra non. Integer in pellentesque velit. Sed rhoncus sem quis lectus posuer',
      quantity:1,
      img:'https://atlas-content-cdn.pixelsquid.com/assets_v2/187/1877473195406136490/jpeg-600/G03.jpg',
      review:20,
      rating:5,

    },{
      name:'dmerger purse',
      category:'male bags',
      brand:'dmerger',
      class:'fashion bag',
      price:12000,
      details:'Phasellus scelerisque egestas gravida. Mauris vehicula quis eros ac venenatis. Morbi eleifend lacus dolor, sed condimentum sapien facilisis a. Donec pharetra aliquam augue, dictum sagittis nibh pharetra non. Integer in pellentesque velit. Sed rhoncus sem quis lectus posuer',
      quantity:1,
      img:'https://www.dmarge.com/wp-content/uploads/2021/01/best-sling-bags-for-men-everlane-920x920.jpg',
      review:30,
      rating:5,

    },
    {
      name:'amazons east',
      category:'male bags',
      brand:'amazona',
      class:'fashion bag',
      price:30000,
      details:'Phasellus scelerisque egestas gravida. Mauris vehicula quis eros ac venenatis. Morbi eleifend lacus dolor, sed condimentum sapien facilisis a. Donec pharetra aliquam augue, dictum sagittis nibh pharetra non. Integer in pellentesque velit. Sed rhoncus sem quis lectus posuer',
      quantity:1,
      img:'https://s3.us-east-2.amazonaws.com/ccp-prd-s3-uploads/2021/10/7/7fb2df97f9564bf36012c0c005e65e759e1b23ce.jpeg',
      review:30,
      rating:4,
    },
    {
      name:'Men shoe',
      category:'popular',
      brand:'men shizzy',
      class:'male shoes',
      price:12000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://pngimg.com/uploads/men_shoes/men_shoes_PNG7476.png',
      review:12,
      rating:5,
    },
    {
      name:'leather boot',
      category:'popular',
      brand:'givenchy',
      class:'male shoes',
      price:20000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://www.pngall.com/wp-content/uploads/5/Brown-Men-Shoes-PNG.png',
      review:30,
      rating:5,
    },
    {
      name:'fine sandals',
      category:'popular',
      brand:'cras della',
      class:'male shoes',
      price:5000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://icon2.cleanpng.com/20180323/eaq/kisspng-slipper-footwear-shoe-sandal-flip-flops-men-shoes-5ab57871171a07.8676672615218422890946.jpg',
      review:50,
      rating:5,
    },
    {
      name:'Nike sneaker',
      category:'popular',
      brand:'Nike',
      class:'male shoes',
      price:15000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://p7.hiclipart.com/preview/249/485/299/shoe-running-sneakers-clothing-nike-running-shoes-png-image.jpg',
      review:30,
      rating:5,
    },
    {
      name:'red vintage',
      category:'popular',
      brand:'vintage',
      class:'male shoes',
      price:34000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://thumbs.dreamstime.com/b/vintage-red-shoes-23151148.jpg',
      review:40,
      rating:5,
    },
    {
      name:'Black heel',
      category:'popular',
      brand:'nice ink',
      class:'female shoes',
      price:18000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://www.nicepng.com/png/detail/24-242136_black-pointed-toe-high-heel-ankle-boots-black.png',
      review:60,
      rating:5,
    },
    {
      name:'browwn flat',
      category:'popular',
      brand:'ducci',
      class:'female shoes',
      price:4000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://media.istockphoto.com/photos/pair-of-beige-female-shoes-on-white-background-picture-id585765638?k=20&m=585765638&s=170667a&w=0&h=-cUsHwTxYJkd7C-7FNjkWZ-qB4M0hSzbHnqxAF4Bmeo=',
      review:17,
      rating:5,
    },
    {
      name:'glass heel',
      category:'popular',
      brand:'can stock',
      class:'female shoes',
      price:23000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://cdn.xxl.thumbs.canstockphoto.com/womens-legs-in-transparent-shoes-white-background-shoes-are-decorated-with-rhinestones-pictures_csp100127867.jpg',
      review:70,
      rating:5,
    },
    {
      name:'cute shoe',
      category:'popular',
      brand:'click art',
      class:'female shoes',
      price:10000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://cutewallpaper.org/24/womens-shoes-cliparts/19236422.jpg',
      review:60,
      rating:5,
    },
    {
      name:'woman blue',
      category:'popular',
      brand:'ble vy',
      class:'female shoes',
      price:4500,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://pngimg.com/uploads/women_shoes/women_shoes_PNG7448.png',
      review:40,
      rating:5,
    },
    {
      name:'bag set',
      category:'popular',
      brand:'gucci',
      class:'female bag',
      price:1000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://toppng.com/uploads/preview/ucci-bag-style-gucci-women-bag-2018-11562991370txnmsfbgun.png',
      review:18,
      rating:5,
    },
    {
      name:'classy bagsz',
      category:'popular',
      brand:'jenny',
      class:'female bag',
      price:12700,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://www.vhv.rs/dpng/d/444-4447393_women-bag-png-free-images-women-hand-bags.png',
      review:45,
      rating:4.5,
    },
    {
      name:'dapibus',
      category:'popular',
      brand:'congque',
      class:'female bag',
      price:12000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm5aplXbbN8eSSA26IJiItsR2V-opgQDuVuZdoibA8Jy63SIL_GTuF8GO2w2S-ZmRwcLU&usqp=CAU',
      review:20,
      rating:5,
    },
    {
      name:'nikky gab',
      category:'popular',
      brand:'nikky huz',
      class:'female bag',
      price:12000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://ph-live-01.slatic.net/p/51424561f45f0b0a184b2ccb5e3c6859.jpg',
      review:19,
      rating:4,
    },
    {
      name:'kless cog',
      category:'popular',
      brand:'clops',
      class:'female bag',
      price:15500,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://cdn11.bigcommerce.com/s-pkla4xn3/images/stencil/1280x1280/products/15041/145554/Free-shipping-2018-new-woman-trend-handbags-leisure-messenger-bag-retro-Korean-version-women-bag-fashion__68546.1544528646.jpg',
      review:10,
      rating:5,
    },
    {
      name:'yulky bag',
      category:'popular',
      brand:'yulyk',
      class:'male bags',
      price:23000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://toppng.com/uploads/preview/school-bags-for-high-school-boys-11553968229fizhcw9rfw.jpg',
      review:19,
      rating:5,
    },
    {
      name:'nekeked bag',
      category:'popular',
      brand:'nekkee',
      class:'male bags',
      price:17000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://icon2.cleanpng.com/20180723/lcv/kisspng-taobao-tmall-goods-import-price-men-bag-5b56998262ea45.2114540115324020504052.jpg',
      review:50,
      rating:5,
    },
    {
      name:'butty bag',
      category:'popular',
      brand:'butty',
      class:'male bags',
      price:30000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://mpng.subpng.com/20180302/tdw/kisspng-messenger-bag-shoulder-euclidean-vector-men-s-shoulder-bag-business-bag-5a997fe83622c6.9678091715200091922218.jpg',
      review:30,
      rating:5,
    },
    {
      name:'oppen bag',
      category:'popular',
      brand:'open',
      class:'male bags',
      price:12000,
      details:'Cras vestibulum dapibus nibh, non congue ex. Cras porta sagittis enim vel tincidunt. Maecenas tincidunt, magna at tristique sollicitudin, risus ante lacinia tellus, non maximus eros lorem vitae purus. Pellentesque sapien nisl, faucibus ut tincidunt vitae, tincidunt eget nisl. In nunc lorem, feugiat quis mauris eget, aliquet elementum velit. Donec sodales et neque in eleifend.',
      quantity:1,
      img:'https://mpng.subpng.com/20180302/tdw/kisspng-messenger-bag-shoulder-euclidean-vector-men-s-shoulder-bag-business-bag-5a997fe83622c6.9678091715200091922218.jpg',
      review:61,
      rating:5,
    }
  ]
};

export default data;